### ISSUE TITLE
Not being able to convert certain sticker

### ISSUE THREAD

**Issue by Vanielleeissb** [iomintz/Adhesive#11]
Hello,
First. Thank you so much for this little fix. I love it. Unfortunately, when trying to convert my favourite sticker collection from Telegram to signal, some just couldn't be converted. It also seems random to me which can, or cannot be converted (they are all in animated). The error is reproducable. When you send the bot a sticker, he responses and the process starts, but instead of a result I will get the message "An internal error occurred while trying to run that command. Hey if you see the owner, give them this code okay? 14818712013640352576" with the number changing each time. Happened with 3/6 of my sticker packs.

**Comment by ioistired** [comment]
Hi there! I appreciate the feedback. ❤️
Animated packs are not supported at the moment. See #5. As for that particular error code, I'm not sure, as I only keep logs from the past 7 days. The bot was probably rate limited though, see #4.

**Comment by Vanielleeissb** [comment]
The bug has been fixed! All my favorite stickers are now on signal. Also, all the favourite stickers of all of my friends are now on signal. Thanks a lot ❤️❤️❤️Isabelle Vins-------- Original message --------From: iomintz <notifications@github.com>Date: Wed, 3 Feb 2021, 05:12To: signalstickers/Adhesive <Adhesive@noreply.github.com>Cc: Vanielleeissb <isabelle.vins@rub.de>, Author <author@noreply.github.com>Subject: Re: [signalstickers/Adhesive] Not being able to convert certain sticker (#11)

Hi there! I appreciate the feedback. ❤️

Animated packs are not supported at the moment. See #5. As for that particular error code, I'm not sure, as I only keep logs from the past 7 days. The bot was probably rate limited though, see #4.
