### ISSUE TITLE
No any respond on telegram app

### ISSUE THREAD

**Issue by tiffanyyy9** [iomintz/Adhesive#17]
Hi When I apply start or send the sticker link on the telegram app. No any respond. And it already fews day issue. Even del and reopen the bot. It still no respone.
![55530167-E6A7-4FB2-A049-822A6550A8BD](https://user-images.githubusercontent.com/93037663/138554269-a244af1b-167f-4338-8e9a-cbb643445d60.jpeg)

**Comment by FelikZ** [comment]
Same here! Use to work flawlessly last month

**Comment by dired** [comment]
true

**Comment by ioistired** [comment]
Yes, the bot is down right now. I'll work on bringing it back up.

**Comment by ioistired** [comment]
Fixed.
