### ISSUE TITLE
Did the bot block me? How to get unblocked?

### ISSUE THREAD

**Issue by rugk** [iomintz/Adhesive#21]
My Telegram account seems to have been blocked. I submitted and published a lot of stickers in the last months, and even if I send a non-animated sticker pack, I do not get any reply anymore… 

How can I get unblocked?

**Comment by ioistired** [comment]
You're not blocked. The bot is just down right now. I'll work on bringing it back up this weekend.

**Comment by rugk** [comment]
Okay 3 days ago or so it worked. Is it down again now though?👀

**Comment by ioistired** [comment]
no
