### ISSUE TITLE
Numeric error when trying to submit to signalstickers.com

### ISSUE THREAD

**Issue by rugk** [iomintz/Adhesive#22]
I was supposed to give that to you:
> An internal error occurred while trying to run that command. Hey if you see the owner, give them this code okay? 3305526389975229324

Tried again and here is another round:
> An internal error occurred while trying to run that command. Hey if you see the owner, give them this code okay? 5703161261181087732

**Comment by romainricard** [comment]
Hello, can you try again? There was a maintenance operation going on signalstickers' backend host. It should now be resolved!

**Comment by rugk** [comment]
Yeah works now. And it seems the stickers I submitted before still were correctly submitted.

Though is there any way to improve the error messages? I dunno whether these random numbers help anyone.🙃

**Comment by rugk** [comment]
Oh no forget it, still need to submit the old sticker packs.

**Comment by rugk** [comment]
Just got another error. Maintainance again?

> An internal error occurred while trying to run that command. Hey if you see the owner, give them this code okay? 14236809689368361992

**Comment by romainricard** [comment]
Yup.. 😣![Screenshot_20220427-192558_1.png](https://user-images.githubusercontent.com/7778898/165584748-5d9f54ec-b242-4830-a923-34800f4891b2.png)

**Comment by romainricard** [comment]
This time it should be fixed for good! Do not hesitate to reopen this Issue if this keeps happening. Thanks for the feedbacks!
