### ISSUE TITLE
the bot on telegram does not work

### ISSUE THREAD

**Issue by nanopone** [iomintz/Adhesive#28]
AdhesiveStickerBot has stopped functioning, it seems

![Screenshot_20230830-164322_Telegram](https://github.com/signalstickers/Adhesive/assets/49787675/9185b3bd-e2c0-450d-99ca-8b1dfe5eb93b)

**Comment by abhitrueprogrammer** [comment]
Can confirm.

**Comment by farline99** [comment]
same here. bruh situation.

**Comment by Shadow-Hunt3r** [comment]
Same here, except that giving it a signal sticker pack causes it to say that the sticker pack is not found

**Comment by gorbak25** [comment]
+1

**Comment by gorbak25** [comment]
![image](https://github.com/signalstickers/Adhesive/assets/1352848/83c216e5-e0cc-40d4-a59c-104befc8d3da)

**Comment by Swiftloke** [comment]
+1. The Telegram bot continues to be offline with the same error messages as above.

**Comment by swindlesmccoop** [comment]
Telegram bot seems to be reading messages but doesn't respond at all.

**Comment by furdiburd** [comment]
Bot is still down. It does not respond

**Comment by ioistired** [comment]
The bot is currently down as I can no longer afford a server to host it on. Also, I lost access to my Telegram account. I will leave this issue open as a reminder for myself, however, please do not expect any ETA for this to be fixed.

**Comment by furdiburd** [comment]
Just another question. Technicaly around how much would it cost to get it running again?

**Comment by ioistired** [comment]
$5/month for a VPS + 30¢ for a Telegram account

**Comment by ioistired** [comment]
OK, I have a Telegram account again (for anyone wondering, do not use forks or unofficial Telegram builds if you need a code sent via SMS), but still no money for a VPS.

**Comment by nanopone** [comment]
i can happily host the bot on my vps if needed

**Comment by ioistired** [comment]
Cool. What's your Telegram handle? If you don't feel comfortable disclosing, you can email it to me gie9ohbeixah@paperboats.net.

**Comment by nanopone** [comment]
> Cool. What's your Telegram handle? If you don't feel comfortable disclosing, you can email it to me [gie9ohbeixah@paperboats.net](mailto:gie9ohbeixah@paperboats.net).

i recently stopped using telegram and migrated to signal (ironically, lol) but my account is still active at https://t.me/nanopone

**Comment by ioistired** [comment]
With thanks to @nanopone, Adhesive now has a new home.

**Comment by farline99** [comment]
@ioistired, awesome news but bot still does not work.

"An internal error occurred while trying to run that command. Hey if you see the owner, give them this code okay? 2836347000858364416".

**Comment by Commenter25** [comment]
i'm getting that too, but if you try it again it'll eventually work
